import json
from typing import Any

from .request import Request


class Oai3Json:
    requests: Any = None
    formatted: Any = None
    models: Any = None
    security_schemes: Any = None
    component_parameters: Any = None
    component_responses: Any = None
    component_request_bodies: Any = None
    component_headers: Any = None
    component_examples: Any = None
    component_links: Any = None
    component_callbacks: Any = None

    def __init__(self, oai3_schema_resolver):
        self.oai3_schema_resolver = oai3_schema_resolver
        self.requests = []
        self.formatted = []
        self.models = {}
        self.component_parameters = {}
        self.component_responses = {}
        self.component_request_bodies = {}
        self.component_headers = {}
        self.component_examples = {}
        self.component_links = {}
        self.component_callbacks = {}

    def set_requests(self, requests):
        self.requests = requests
        self.formatted = [self.format_request(request) for request in self.requests]

    def set_components(self, components):
        supported = [
            "models",
            "securitySchemes",
            "parameters",
            "responses",
            "requestBodies",
            "headers",
            "examples",
            "links",
            "callbacks",
        ]
        for key in components.keys():
            if key not in supported:
                raise ValueError(
                    f"Attempt to set unsupported OpenAPI3.0 component which is not currently supported: {key}"
                )
        if "models" in components:
            self.set_models(components["models"])
        if "securitySchemes" in components:
            self.set_security_schemes(components["securitySchemes"])
        if "parameters" in components:
            self.set_parameters(components["parameters"])
        if "responses" in components:
            self.set_responses(components["responses"])
        if "requestBodies" in components:
            self.set_request_bodies(components["requestBodies"])
        if "headers" in components:
            self.set_headers(components["headers"])
        if "examples" in components:
            self.set_examples(components["examples"])
        if "links" in components:
            self.set_links(components["links"])
        if "callbacks" in components:
            self.set_callbacks(components["callbacks"])

    def set_models(self, models):
        self.models = models

    def set_security_schemes(self, security_schemes):
        self.security_schemes = security_schemes

    def set_parameters(self, parameters):
        self.component_parameters = parameters

    def set_responses(self, responses):
        self.component_responses = responses

    def set_request_bodies(self, request_bodies):
        self.component_request_bodies = request_bodies

    def set_headers(self, headers):
        self.component_headers = headers

    def set_examples(self, examples):
        self.component_examples = examples

    def set_links(self, links):
        self.component_links = links

    def set_callbacks(self, callbacks):
        self.component_callbacks = callbacks

    def format_request(self, request):
        formatted_request = Request(self.oai3_schema_resolver)
        formatted_request.set_request(request)
        return formatted_request

    def pretty(self, root_properties=None):
        return self.as_string(pretty=True, root_properties=root_properties)

    def compact(self, root_properties=None):
        return self.as_string(pretty=False, root_properties=root_properties)

    def as_string(self, pretty=False, root_properties=None):
        data = self.convert()
        if root_properties is not None:
            data = {**data, **root_properties}
        if pretty:
            return json.dumps(data, indent=2, sort_keys=True)
        return json.dumps(data)

    def convert(self):
        paths: dict[str, Any] = {}
        for request in self.formatted:
            absolute_path = "/" + request.relative_path.lstrip("/")
            if absolute_path not in paths:
                paths[absolute_path] = {}

            path_data = request.convert()
            for request_method, path_doc in path_data.items():
                if request_method in paths[absolute_path]:
                    continue
                paths[absolute_path][request_method] = path_doc

        data: dict[str, Any] = {
            "openapi": "3.0.0",
            "info": {
                "title": "Auto generated by clearskies",
                "version": "1.0",
            },
            "paths": paths,
        }

        # Only add components if we have schemas or security schemes
        components: dict[str, Any] = {}

        if self.models:
            components["schemas"] = {
                model_name: self.oai3_schema_resolver(model).convert() for (model_name, model) in self.models.items()
            }

        if self.security_schemes:
            components["securitySchemes"] = {name: scheme_data for (name, scheme_data) in self.security_schemes.items()}

        if self.component_parameters:
            components["parameters"] = self.component_parameters

        if self.component_responses:
            components["responses"] = self.component_responses

        if self.component_request_bodies:
            components["requestBodies"] = self.component_request_bodies

        if self.component_headers:
            components["headers"] = self.component_headers

        if self.component_examples:
            components["examples"] = self.component_examples

        if self.component_links:
            components["links"] = self.component_links

        if self.component_callbacks:
            components["callbacks"] = self.component_callbacks

        # Only include components key if it has content
        if components:
            data["components"] = components

        return data
