import json
import unittest

from clearskies.autodoc.formats.oai3_json import Oai3Json, OAI3SchemaResolver
from clearskies.autodoc.request import Request
from clearskies.autodoc.response import Response
from clearskies.autodoc.schema import String


class TestOai3DocumentRoot(unittest.TestCase):
    def _request(self):
        response = Response(schema=String("message"), status=200, description="Ok")
        return Request(
            description="Health",
            responses=[response],
            relative_path="/health",
            request_methods=["GET"],
        )

    def test_default_info_is_present(self):
        oai3_json = Oai3Json(OAI3SchemaResolver())
        oai3_json.set_requests([self._request()])

        output = json.loads(oai3_json.compact())
        self.assertIn("info", output)
        self.assertEqual(output["info"]["title"], "Auto generated by clearskies")
        self.assertEqual(output["info"]["version"], "1.0")

    def test_root_metadata_overrides_defaults_and_adds_servers(self):
        oai3_json = Oai3Json(OAI3SchemaResolver())
        oai3_json.set_requests([self._request()])

        output = json.loads(
            oai3_json.compact(
                root_properties={
                    "info": {
                        "title": "M2M Dynamic producers",
                        "version": "1.0a",
                        "summary": "Dynamic prodcuers that handle m2m auth.",
                        "description": "This a server that can be used for Akeyless to serve dynamic m2m authentication.",
                        "contact": {
                            "name": "Cimpress Security",
                            "email": "security@cimpress.com",
                        },
                    },
                    "servers": [
                        {
                            "url": "https://staging-m2m.dynamic-producer.secrets.cimpress.io",
                            "description": "Staging",
                        },
                        {
                            "url": "https://m2m.dynamic-producer.secrets.cimpress.io",
                            "description": "Production",
                        },
                    ],
                }
            )
        )

        self.assertEqual(output["info"]["title"], "M2M Dynamic producers")
        self.assertEqual(output["info"]["version"], "1.0a")
        self.assertIn("servers", output)
        self.assertEqual(len(output["servers"]), 2)


if __name__ == "__main__":
    unittest.main()
