name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Publish New Version to Pypi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Fetch pypi token from Akeyless
        uses: LanceMcCarthy/akeyless-action@d42e07875b1cc7162afd290722babbaf879a86e6
        id: fetch-secrets
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          static-secrets: '{"/pypi":"pypi"}'
      - uses: ./.github/actions/bootstrap-poetry
      - name: Publish
        run: |
          echo 'Building version ${{ github.ref_name }}'
          sed -i 's/VERSION/${{ github.ref_name }}/' pyproject.toml
          poetry build
          poetry publish --username __token__ --password ${{ steps.fetch-secrets.outputs.pypi }}
